import { UserProfile, ExportProduct, ExportShipment, Certification, ExportDocument, RealTimeAlert, ShipmentStep, UserRole } from './types';

export const mockUsers: UserProfile[] = [
  {
    id: 'usr-admin',
    name: 'Budi Raharjo',
    role: 'Owner/Direktur',
    email: 'admin@exportflow.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    companyName: 'Kementerian Perdagangan & Bea Cukai (Bea Cukai RI)',
    phone: '+6281234567890',
  },
  {
    id: 'usr-trader',
    name: 'Hendry Kurniawan',
    role: 'Trader',
    email: 'hendry@nusantara-traders.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    companyName: 'PT Multi Raksa Madani',
    address: 'Sudirman Central Business District, Jakarta',
    country: 'Indonesia',
    phone: '+6281122334455',
  },
  {
    id: 'usr-buyer',
    name: 'Hans Mueller',
    role: 'Buyer',
    email: 'hans.m@eurofoods-import.de',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    companyName: 'EuroFoods Import GmbH',
    address: 'Kaiserstraße 12, Frankfurt am Main',
    country: 'Germany',
    phone: '+491701234567',
  },
  {
    id: 'usr-forwarder',
    name: 'Siti Aminah',
    role: 'Forwarder',
    email: 'siti.aminah@samuderatrans.co.id',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    companyName: 'PT Samudera Logistik Internasional',
    address: 'Tanjung Priok Port Area, Jakarta',
    country: 'Indonesia',
    phone: '+6285799887766',
  },
  {
    id: 'usr-supplier',
    name: 'Wayan Karang',
    role: 'Supplier',
    email: 'wayan@organic-bali-spices.com',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150',
    companyName: 'Koperasi Tani rempah Organik Bali',
    address: 'Kintamani, Bangli, Bali',
    country: 'Indonesia',
    phone: '+6281353535353',
  },
];

export const mockProducts: ExportProduct[] = [
  {
    id: 'prod-1',
    name: 'Premium Coconut Shell Charcoal Briquette',
    category: 'Energi Terbarukan / Arang Kelapa',
    hsCode: '4402.20.10',
    price: '1,450',
    unit: 'Metrik Ton (MT)',
    specification: 'Kadar air < 5%, Kalori > 7500 Kcal, Abu < 2.5%, Tanpa bahan kimia beracun, ukuran kubus 25x25x25mm.',
    image: 'https://images.unsplash.com/photo-1608686207856-001b95cf60ca?w=400',
    supplierName: 'Koperasi Arang Kelapa Berkah Halmahera',
    origin: 'Halmahera, Maluku Utara',
    minOrder: '20 MT (1 Kontainer FCL 20ft)',
  },
  {
    id: 'prod-2',
    name: 'Organic Gayo Arabica Coffee Beans (Grade 1)',
    category: 'Pertanian / Kopi',
    hsCode: '0901.11.10',
    price: '6,200',
    unit: 'Metrik Ton (MT)',
    specification: 'Kadar air 12%, Defect rate < 4%, Double pick, Ketinggian 1400 MDPL, Proses Basah Giling basah (Wet Hulled).',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400',
    supplierName: 'Koperasi Kopi Gayo Organik - Aceh Tengah',
    origin: 'Aceh Tengah, Sumatra',
    minOrder: '10 MT',
  },
  {
    id: 'prod-3',
    name: 'Premium Whole Nutmeg (Pala Kupas ABCD)',
    category: 'Pertanian / Rempah-rempah',
    hsCode: '0908.11.00',
    price: '8,400',
    unit: 'Metrik Ton (MT)',
    specification: 'Kadar air < 10%, Bebas jamur/aflatoksin, Pala kupas utuh tanpa retak, sertifikasi Phytosanitary terlampir.',
    image: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=400',
    supplierName: 'Koperasi Tani rempah Organik Bali',
    origin: 'Banda Neira, Maluku & Bali',
    minOrder: '5 MT',
  },
  {
    id: 'prod-4',
    name: 'Refined Bleached Deodorized Palm Olein (RBDPL) IV 57',
    category: 'Minyak Nabati / CPO',
    hsCode: '1511.90.31',
    price: '1,050',
    unit: 'Metrik Ton (MT)',
    specification: 'Color 3.0 Red Max, FFA 0.1% Max, M&I 0.1% Max, IV 57 Min, Cloud point 8.0 Celcius Max.',
    image: 'https://images.unsplash.com/photo-1622484211148-71749840bcec?w=400',
    supplierName: 'PT Sinar Lestari Sawit Indonesia',
    origin: 'Sampit, Kalimantan Tengah',
    minOrder: '100 MT',
  },
  {
    id: 'prod-5',
    name: 'Natural Desiccated Coconut High Fat (Fine Grade)',
    category: 'Pengolahan Kelapa',
    hsCode: '0801.11.10',
    price: '1,800',
    unit: 'Metrik Ton (MT)',
    specification: 'Fat Content 65% Min, Moisture 3% Max, Free Fatty Acid 0.3% Max, SO2 free, Bebas Salmonella.',
    image: 'https://images.unsplash.com/photo-1550592755-cb0c0fc33827?w=400',
    supplierName: 'PT Celebes Coconut Industri',
    origin: 'Minahasa, Sulawesi Utara',
    minOrder: '12 MT',
  }
];

export const mockCertificationsList = (shipmentId: string): Certification[] => [
  {
    id: `cert-${shipmentId}-1`,
    name: 'Sertifikat Phytosanitary (Karantina Tumbuhan)',
    code: 'PHYT-ID-2026-90812',
    description: 'Menjamin produk pertanian bebas hama & penyakit karantina, diterbitkan oleh Badan Karantina Indonesia.',
    authority: 'Badan Karantina Indonesia (Barantin)',
    requiredFor: 'Semua komoditas hasil bumi/pertanian',
    status: 'Verified',
    expiryDate: '2026-12-15',
    uploadedUrl: '#',
    updatedAt: '2026-06-12T10:00:00Z',
  },
  {
    id: `cert-${shipmentId}-2`,
    name: 'Sertifikat Halal Indonesia (BPJPH)',
    code: 'HALAL-ID-312100045812',
    description: 'Sertifikasi jaminan produk halal untuk konsumsi pangan dan komoditas pendukung.',
    authority: 'Badan Penyelenggara Jaminan Produk Halal (BPJPH)',
    requiredFor: 'Komoditas pangan, kopi, rempah-rempah eksportasi negara Muslim',
    status: 'Verified',
    expiryDate: '2030-05-20',
    uploadedUrl: '#',
    updatedAt: '2026-06-11T14:30:00Z',
  },
  {
    id: `cert-${shipmentId}-3`,
    name: 'Certificate of Origin (COO / SKA Form-A/D/E)',
    code: 'COO-SKA-JKT-19028',
    description: 'Surat Keterangan Asal membuktikan barang berasal dari Indonesia untuk pemotongan tarif pabean preferensil.',
    authority: 'Dinas Perindustrian dan Perdagangan DKI Jakarta',
    requiredFor: 'Keringanan bea masuk di negara mitra dagang rujukan',
    status: 'In Progress',
    updatedAt: '2026-06-18T09:15:00Z',
  },
  {
    id: `cert-${shipmentId}-4`,
    name: 'Sertifikat Sistem Manajemen Keamanan Pangan (HACCP)',
    code: 'HACCP-SMKP-2026-004a',
    description: 'Sertifikasi uji titik kritis pengolahan makanan higienis standar ekspor internasional.',
    authority: 'Komite Akreditasi Nasional (KAN)',
    requiredFor: 'Keamanan pangan Uni Eropa, Amerika Serikat, & Jepang',
    status: 'Pending',
    updatedAt: '2026-06-10T16:00:00Z',
  }
];

export const createMockDocuments = (shipmentId: string, value: number, qty: number, unit: string, prodName: string, hsCode: string): ExportDocument[] => [
  {
    id: `doc-${shipmentId}-1`,
    shipmentId,
    type: 'Sales Contract',
    code: `SC/NGL/${shipmentId.slice(-4).toUpperCase()}/2026`,
    title: 'Sales Contract Agreement',
    status: 'Approved',
    createdBy: 'usr-trader',
    createdAt: '2026-06-01T08:00:00Z',
    updatedAt: '2026-06-02T15:00:00Z',
    issuedDate: '2026-06-02',
    details: {
      exporter: 'PT Multi Raksa Madani\nSudirman Central Business District, Jakarta, Indonesia',
      importer: 'EuroFoods Import GmbH\nKaiserstraße 12, Frankfurt am Main, Germany',
      paymentTerms: 'L/C (Letter of Credit) at sight',
      items: [
        {
          description: prodName,
          hsCode: hsCode,
          quantity: qty,
          unit: unit,
          unitPrice: value / qty,
          totalPrice: value,
        }
      ],
      totalAmount: value,
      additionalNotes: 'FOB Tanjung Priok Port, Jakarta. Dispute settlement shall be conducted at BANI (Indonesian National Board of Arbitration).'
    }
  },
  {
    id: `doc-${shipmentId}-2`,
    shipmentId,
    type: 'Commercial Invoice',
    code: `INV/NGL-${shipmentId.slice(-4).toUpperCase()}/236`,
    title: 'Commercial Invoice',
    status: 'Issued',
    createdBy: 'usr-trader',
    createdAt: '2026-06-03T10:00:00Z',
    updatedAt: '2026-06-18T11:00:00Z',
    issuedDate: '2026-06-18',
    details: {
      exporter: 'PT Multi Raksa Madani\nSudirman Central Business District, Jakarta, Indonesia',
      importer: 'EuroFoods Import GmbH\nKaiserstraße 12, Frankfurt am Main, Germany',
      portOfLoading: 'Tanjung Priok, Jakarta (IDTPP)',
      portOfDischarge: 'Port of Hamburg, Germany (DEHAM)',
      vesselName: 'MV Samudera Pasifik V.204',
      paymentTerms: 'L/C at Sight No. LC-9831-2026',
      shippingMark: 'EF / NUTMEG / FRANKFURT\nNO. 1 - 250\nMADE IN INDONESIA',
      items: [
        {
          description: prodName,
          hsCode: hsCode,
          quantity: qty,
          unit: unit,
          unitPrice: value / qty,
          totalPrice: value,
        }
      ],
      totalAmount: value,
      weightNet: `${qty * 1000 - 150} Kgs`,
      weightGross: `${qty * 1000} Kgs`,
      additionalNotes: 'Commercial Invoice created by Trader for Customs verification.'
    }
  },
  {
    id: `doc-${shipmentId}-3`,
    shipmentId,
    type: 'Packing List',
    code: `PL/NGL-${shipmentId.slice(-4).toUpperCase()}/236`,
    title: 'Packing List',
    status: 'Issued',
    createdBy: 'usr-trader',
    createdAt: '2026-06-03T10:15:00Z',
    updatedAt: '2026-06-18T11:00:00Z',
    issuedDate: '2026-06-18',
    details: {
      exporter: 'PT Multi Raksa Madani\nSudirman Central Business District, Jakarta, Indonesia',
      importer: 'EuroFoods Import GmbH\nKaiserstraße 12, Frankfurt am Main, Germany',
      portOfLoading: 'Tanjung Priok, Jakarta',
      portOfDischarge: 'Port of Hamburg, Germany',
      vesselName: 'MV Samudera Pasifik V.204',
      shippingMark: 'EF / NUTMEG / FRANKFURT\nNO. 1 - 250\nMADE IN INDONESIA',
      items: [
        {
          description: prodName + ' packed in 250 Double PP Gunny Bags',
          hsCode: hsCode,
          quantity: qty,
          unit: unit,
          unitPrice: value / qty,
          totalPrice: value,
        }
      ],
      totalAmount: value,
      weightNet: `${qty * 1000 - 150} Kgs`,
      weightGross: `${qty * 1000} Kgs`,
      additionalNotes: 'Total cargo packing container: 1x20 Feet Dry Cargo Container.'
    }
  },
  {
    id: `doc-${shipmentId}-4`,
    shipmentId,
    type: 'Bill of Lading',
    code: `BL/NGL/SITI-9018A`,
    title: 'Ocean Bill of Lading (B/L)',
    status: 'Draft',
    createdBy: 'usr-forwarder',
    createdAt: '2026-06-17T09:00:00Z',
    updatedAt: '2026-06-18T17:00:00Z',
    details: {
      exporter: 'PT Multi Raksa Madani\nSudirman Central Business District, Jakarta, Indonesia',
      importer: 'EuroFoods Import GmbH\nKaiserstraße 12, Frankfurt am Main, Germany',
      portOfLoading: 'Tanjung Priok, Jakarta (IDTPP)',
      portOfDischarge: 'Port of Hamburg, Germany (DEHAM)',
      vesselName: 'MV Samudera Pasifik V.204',
      paymentTerms: 'Ocean Freight Prepaid',
      shippingMark: 'EF / NUTMEG / FRANKFURT\nCONTAINER NO: TGBU-918231-0 / SEAL NO: ID-912838',
      items: [
        {
          description: `1 x 20 FCL Container containing ${qty} ${unit} of ${prodName}`,
          hsCode: hsCode,
          quantity: qty,
          unit: unit,
          unitPrice: value / qty,
          totalPrice: value,
        }
      ],
      totalAmount: value,
      weightNet: `${qty * 1000 - 150} Kgs`,
      weightGross: `${qty * 1000} Kgs`,
      additionalNotes: 'Shipped in apparent good order. To order of Buyer. Carrier is Samudera Logistik.'
    }
  }
];

export const initialShipments = (): ExportShipment[] => [
  {
    id: 'ship-1001',
    contractNumber: 'SC/NGL/PL-2026-001',
    buyerId: 'usr-buyer',
    buyerName: 'Hans Mueller',
    buyerCompany: 'EuroFoods Import GmbH (München)',
    supplierId: 'usr-supplier',
    supplierName: 'Wayan Karang',
    supplierCompany: 'Koperasi Tani rempah Organik Bali',
    forwarderId: 'usr-forwarder',
    forwarderName: 'Siti Aminah',
    forwarderCompany: 'PT Samudera Logistik Internasional',
    traderId: 'usr-trader',
    traderName: 'Hendry Kurniawan',
    productName: 'Premium Whole Nutmeg (Pala Kupas ABCD)',
    quantity: 10,
    unit: 'Metrik Ton (MT)',
    totalValue: 84000,
    currency: 'USD',
    hsCode: '0908.11.00',
    portOfLoading: 'Tanjung Priok (IDTPP), Jakarta',
    portOfDischarge: 'Port of Hamburg (DEHAM), Germany',
    vesselName: 'MV Samudera Pasifik',
    voyageNumber: 'V.204W',
    etd: '2026-06-25',
    eta: '2026-07-28',
    trackingNumber: 'SMDR-NT-9821389',
    currentStep: 'Draft',
    stepHistory: [
      { step: 'Draft', timestamp: '2026-06-01T09:00:00Z', updatedBy: 'usr-trader', comments: 'Sales contract ditandatangani oleh Buyer & Trader.' }
    ],
    documents: [],
    certifications: []
  },
  {
    id: 'ship-1002',
    contractNumber: 'SC/NGL/COF-2026-002',
    buyerId: 'usr-buyer',
    buyerName: 'Hans Mueller',
    buyerCompany: 'EuroFoods Import GmbH (München)',
    supplierId: 'usr-supplier',
    supplierName: 'Bapak Gayo Coffee Group',
    supplierCompany: 'Koperasi Kopi Gayo Organik',
    forwarderId: 'usr-forwarder',
    forwarderName: 'Siti Aminah',
    forwarderCompany: 'PT Samudera Logistik Internasional',
    traderId: 'usr-trader',
    traderName: 'Hendry Kurniawan',
    productName: 'Organic Gayo Arabica Coffee Beans (Grade 1)',
    quantity: 20,
    unit: 'Metrik Ton (MT)',
    totalValue: 124000,
    currency: 'USD',
    hsCode: '0901.11.10',
    portOfLoading: 'Ulee Lheue, Banda Aceh / Belawan Port, Medan',
    portOfDischarge: 'Port of Bremerhaven, Germany',
    vesselName: 'MV Global Express',
    voyageNumber: 'V.88A',
    etd: '2026-06-15',
    eta: '2026-07-16',
    trackingNumber: 'GEXP-COF-110294',
    currentStep: 'Draft',
    stepHistory: [
      { step: 'Draft', timestamp: '2026-05-10T09:00:00Z', updatedBy: 'usr-trader', comments: 'Perjanjian Kontrak Selesai.' }
    ],
    documents: [],
    certifications: []
  },
  {
    id: 'ship-1003',
    contractNumber: 'SC/NGL/CHR-2026-003',
    buyerId: 'usr-buyer-frankie',
    buyerName: 'Frankie Shippers Inc.',
    buyerCompany: 'Anatolia Charcoal Distrib',
    supplierId: 'usr-supplier',
    supplierName: 'Koperasi Berkah Maluku',
    supplierCompany: 'Arang Kelapa Berkah Halmahera',
    forwarderId: 'usr-forwarder',
    forwarderName: 'Siti Aminah',
    forwarderCompany: 'PT Samudera Logistik Internasional',
    traderId: 'usr-trader',
    traderName: 'Hendry Kurniawan',
    productName: 'Premium Coconut Shell Charcoal Briquette',
    quantity: 26,
    unit: 'Metrik Ton (MT)',
    totalValue: 37700,
    currency: 'USD',
    hsCode: '4402.20.10',
    portOfLoading: 'Tanjung Perak, Surabaya',
    portOfDischarge: 'Port of Hamburg, Germany',
    vesselName: 'MV Hamburg Pride',
    voyageNumber: 'HP.991',
    etd: '2026-07-02',
    eta: '2026-08-04',
    trackingNumber: 'HMPR-BRQ-332918',
    currentStep: 'Draft',
    stepHistory: [
      { step: 'Draft', timestamp: '2026-06-10T11:00:00Z', updatedBy: 'usr-trader', comments: 'Kontrak disetujui, pembayaran L/C sudah dibuka oleh buyer bank.' }
    ],
    documents: [],
    certifications: []
  },
  {
    id: 'ship-1004',
    contractNumber: 'SC/NGL/CPO-2026-004',
    buyerId: 'usr-buyer',
    buyerName: 'Hans Mueller',
    buyerCompany: 'EuroFoods Import GmbH',
    supplierId: 'usr-supplier',
    supplierName: 'PT Sinar Lestari',
    supplierCompany: 'PT Sinar Lestari Sawit Indonesia',
    forwarderId: 'usr-forwarder',
    forwarderName: 'Siti Aminah',
    forwarderCompany: 'PT Samudera Logistik Internasional',
    traderId: 'usr-trader',
    traderName: 'Hendry Kurniawan',
    productName: 'Refined Bleached Deodorized Palm Olein (RBDPL) IV 57',
    quantity: 200,
    unit: 'Metrik Ton (MT)',
    totalValue: 210000,
    currency: 'USD',
    hsCode: '1511.90.31',
    portOfLoading: 'Port of Sampit, Kalimantan',
    portOfDischarge: 'Port of Rotterdam, Netherlands',
    vesselName: 'MT Golden Palm 09',
    voyageNumber: 'MTGP.002',
    etd: '2026-05-01',
    eta: '2026-05-28',
    trackingNumber: 'GLDP-CPO-77018',
    currentStep: 'Draft',
    stepHistory: [
      { step: 'Draft', timestamp: '2026-04-10T09:00:00Z', updatedBy: 'usr-trader' }
    ],
    documents: [],
    certifications: []
  },
  {
    id: 'ship-1005',
    contractNumber: 'SC/NGL/COF-2026-105',
    buyerId: 'usr-buyer',
    buyerName: 'Hans Mueller',
    buyerCompany: 'EuroFoods Import GmbH (München)',
    supplierId: 'usr-supplier',
    supplierName: 'Kelompok Tani Gunung Gayo',
    supplierCompany: 'Koperasi Kopi Gayo Organik',
    forwarderId: 'usr-forwarder',
    forwarderName: 'Siti Aminah',
    forwarderCompany: 'PT Samudera Logistik Internasional',
    traderId: 'usr-trader',
    traderName: 'Hendry Kurniawan',
    productName: 'Organic Gayo Arabica Coffee Beans (Grade 1)',
    quantity: 20,
    unit: 'Metrik Ton (MT)',
    totalValue: 124000,
    currency: 'USD',
    hsCode: '0901.11.10',
    portOfLoading: 'Port of Belawan, Medan, Indonesia',
    portOfDischarge: 'Port of Hamburg, Germany',
    vesselName: 'MV Hamburg Pride',
    voyageNumber: 'HP.991',
    etd: '2026-07-05',
    eta: '2026-08-08',
    trackingNumber: 'GEXP-COF-110295',
    currentStep: 'Draft',
    stepHistory: [
      { step: 'Draft', timestamp: '2026-06-01T09:00:00Z', updatedBy: 'usr-trader', comments: 'Sales Contract dan Purchase Order resmi disahkan oleh eksportir & importir.' }
    ],
    documents: [],
    certifications: []
  }
];

export const initialAlerts: RealTimeAlert[] = [
  {
    id: 'alt-1',
    shipmentId: 'ship-1001',
    contractNumber: 'SC/NGL/PL-2026-001',
    title: 'Pembaharuan Karantina Tumbuhan',
    message: 'Dokumen Phytosanitary Certificate pala kupas telah divalidasi oleh Balai Pertanian Priok.',
    type: 'success',
    timestamp: '2026-06-19T00:10:00-07:00',
    readBy: [],
  },
  {
    id: 'alt-2',
    shipmentId: 'ship-1002',
    contractNumber: 'SC/NGL/COF-2026-002',
    title: 'Pelacakan Kapal Real-time',
    message: 'Kargo Kopi Gayo (MV Global Express) terdeteksi transit di Terusan Suez, Mesir dalam kondisi stabil.',
    type: 'info',
    timestamp: '2026-06-18T22:30:00-07:00',
    readBy: [],
  },
  {
    id: 'alt-3',
    shipmentId: 'ship-1001',
    contractNumber: 'SC/NGL/PL-2026-001',
    title: 'Jadwal ETD Mendekat',
    message: 'Estimated Time of Departure 6 hari lagi. Pastikan Bill of Lading draf dikonfirmasi oleh Trader sebelum 22 Juni.',
    type: 'warning',
    timestamp: '2026-06-18T18:00:00-07:00',
    readBy: [],
  },
  {
    id: 'alt-4',
    shipmentId: 'ship-1003',
    contractNumber: 'SC/NGL/CHR-2026-003',
    title: 'Kontrak Pembayaran L/C Dibuka',
    message: 'Sistem perbankan mengonfirmasi L/C dari Frankfurt telah tervalidasi untuk transaksi arang briket kelapa.',
    type: 'success',
    timestamp: '2026-06-18T14:50:00-07:00',
    readBy: ['usr-trader'],
  }
];

export const WORKFLOW_STEPS: Array<{
  step: ShipmentStep;
  label: string;
  description: string;
  actor: UserRole;
  expectedDuration: string;
}> = [
  {
    step: 'Draft',
    label: 'Negosiasi & Kontrak',
    description: 'Meja perundingan draf kontrak (LOI, FCO, MoU), penyesuaian klausul secara interaktif secara real-time, dan penandatanganan bilateral Proforma Invoice (PI).',
    actor: 'Trader',
    expectedDuration: '3-7 Hari'
  },
  {
    step: 'Shipping',
    label: 'Proses Logistik & Pencairan L/C',
    description: 'Rangkaian proses terintegrasi mulai dari Sourcing komoditas tani, Kepabeanan Ekspor (COO/PEB), Pelayaran Samudra (B/L), hingga pencairan dana Letter of Credit (L/C).',
    actor: 'Trader',
    expectedDuration: '20-35 Hari'
  },
  {
    step: 'Completed',
    label: 'Selesai & Serah Terima',
    description: 'Kapal berlabuh, barang diclearance di port tujuan (Hamburg), serah terima kargo fisik, dan transaksi ditutup sempurna.',
    actor: 'Buyer',
    expectedDuration: '2-3 Hari'
  }
];
